### ISSUE TITLE
[proxy] too many parallel requests!

### ISSUE THREAD

**Issue by Juweii** [ioBroker/ioBroker.proxy#2] opened 2018-01-29 19:21 UTC
Hello!

Since one of the last updates i can't get my cameras to work.
After restart it works for some minutes but then it stops.
If i open the proxy url in browser, it tells:
[proxy] too many parallel requests!

How can i get rid of this message?

Thank you in advance,
Juergen

**Comment by fiesch** [comment] 2018-03-18 11:06
Reproducible: Open a proxied URL and press f5 10 times -> too many paralle requests. 
It appears as if the requests don't get removed from rule.request. 
This is a bit odd as I -am- getting the 
`[proxy] Response for //[URL]:200(OK)`
per request, so at least
`onProxyRes` gets called, which calls finishReq..
since i have no more log entries from the proxy it appears as if it can find the request... 

So it's down to 
`rule.request.splice(ppos, 1);` (Line 69)

**Comment by fiesch** [comment] 2018-03-18 13:27
wer im richtigen Commit schaut seiht auch dass der Code in "latest" noch nicht drin ist :) nevermind.

**Comment by fiesch** [comment] 2018-03-18 13:42
I can confirm the issue is resolved with current master together with web 2.3.0

**Closed** 2020-04-14 21:01 UTC
